describe('MyLists component user flows', () => {

  it('A user should be able to add a restaurant to either "Wanna try?" or "Loved It"', () => {
    cy.intercept('GET', 'https://fe-cors-proxy.herokuapp.com', { fixture: 'sampleRestaurant.json' })
    .visit('http://localhost:3000')
      .get('#my-lists-nav').click()
      .get('.list-card').should('not.exist')
    
    .visit('http://localhost:3000')
      .get('.dropdown-btn').click()
      .get('dropdown-item').click('[data-cy=gottago]')
      .get('#my-lists-nav').click()
      .get('.list-card').should('exist')
      .get('.delete-button').should('exist')
      .get('.thumbnail').should('exist')
      .get('.name').should('have.text', 'Little Man Ice Cream')
      .get('.rating').should('have.text', 'Rating: 4.5')
      .get('.phone-number').should('have.text', '(303) 455-3811') 
      .get('.address').should('have.text', '2620 16th StDenver, CO 80211')
      .get('.more-info').should('exist') 
      // .get('.more-info').should('have.text', 'Tell Me More')

    .visit('http://localhost:3000')
      .get('.dropdown-btn').click()
      .get('.dropdown-item').first().next().click()
      .get('#my-lists-nav').click()
      .get('.list-button').first().next().click()
      .get('.list-card').should('exist')
      .get('.thumbnail').should('exist')
      .get('.delete-button').should('exist')
      .get('.name').should('have.text', 'Little Man Ice Cream')
      .get('.rating').should('have.text', 'Rating: 4.5')
      .get('.phone-number').should('have.text', '(303) 455-3811') 
      .get('.address').should('have.text', '2620 16th StDenver, CO 80211')
      .get('.more-info').should('exist') 
      // .get('.more-info').should('have.text', 'Tell Me More')
  })

  it('should be able to delete a restaurant from a user\'s lists', () => {
    cy.intercept('GET', 'https://fe-cors-proxy.herokuapp.com', { fixture: 'sampleRestaurant.json' })
      .visit('http://localhost:3000')
        .get('.loved-it').click()
        .get('#my-lists-nav').click()
        .get('.list-dropdown').select('lovedIt')
        .get('.list-card').should('exist')
        .get('.delete-button').click()
        .get('.list-card').should('not.exist')

      .visit('http://localhost:3000')
        .get('.gotta-go').click()
        .get('#my-lists-nav').click()
        .get('.list-card').should('exist')
        .get('.delete-button').click()
        .get('.list-card').should('not.exist')
  })
})